[package]
name = "rust-project"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.76"
base64 = "0.22.1"
image = "0.23.14"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
version = "0.3.4"
features = ["console"]

